@startuml
title BucketAdapter v4

class BucketService {
    + upload(...): ...
    + download(...): ...
    + delete(...): ...
    + list(...): ...
    + doesExist(...): ...
    + share(...): ...
}

class BucketAdapterFactory {
    + getBucketAdapter(): IBucketAdapter
}

interface IBucketAdapter {
    + upload(local, remote):void
    + download(remote, local):void
    + delete(remote, recursive=false):void
    + list(remote, recursive=false): string[]
    + doesExist(remote):boolean
}

class AZUREBucketAdapterImpl
class GCPBucketAdapterImpl
class AWSBucketAdapterImpl

'-- SDK
package AWSSDK{
    class AWSClient
    class IAWSClient
}
package GCPSDK{}
package AZURESDK{}

BucketService --> BucketAdapterFactory
BucketAdapterFactory --> IBucketAdapter

IBucketAdapter <|.. AWSBucketAdapterImpl
IBucketAdapter <|.. GCPBucketAdapterImpl
IBucketAdapter <|.. AZUREBucketAdapterImpl

AWSBucketAdapterImpl *-> AWSClient

AWSBucketAdapterImpl ..> AWSSDK
GCPBucketAdapterImpl ..> GCPSDK
AZUREBucketAdapterImpl ..> AZURESDK

'-- Test

class TestAWSBucketAdapterImpl{
    -mockAWSClient:IAWSClient
}

TestAWSBucketAdapterImpl --> AWSBucketAdapterImpl
TestAWSBucketAdapterImpl <-- IAWSClient:Create
@enduml
